/* automatically generated by rust-bindgen 0.72.1 */

pub type __u64 = ::std::os::raw::c_ulonglong;
pub type u64_ = __u64;
pub type __s32 = ::std::os::raw::c_int;
pub type s32 = __s32;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct skb_drop_event {
    pub drop_reason: s32,
    pub location: u64_,
}
